#day 6 week 2 prompt engineering 
#prompt engineering basic matlab hota hai apne prompt ko behtar banana
#why to learn prompt engineering 
#like hamne last week me llm ke baare me padha and jab hum llm ko baar baar run karte hai na toh hamesha different answer aata hai kyuki llm ka jo behaviour determinsitic nhi hai means har baar wo alag alag answer dega means exactly same nhi aayega but iska problem production me hai means agar jitna stable input rahega na utna stable output aayega because llm ke database me bhi answer store kiya gya hai means agar usse kuch alag swall puchenge toh woh confuse ho jayega then answer as expected nhi aayega jo aana chahiye and dusri baat llm ka koi limit hona chhaiye means customized chahiye means ek fixed prakar ka llm bas fixed answer hi dena chhahiye nahi ki alag alag answer bhi like zomato ka chatbot usse hum apne personal sawal nhi puch skte hai like phir llm ka kuch stable behaviour hoga hi nhi means use ek stable answer dena chahiye irrespective of alag answer ke alawa means zomato ka chatbot ka jisne coding kiya hoga na usne soch ke banaya hoga ki chatbot kisi particular cheez ke liye bana hai aise hi nhi kuch bhi answer puchne ke liye, maanlo agar kisi bhi chatbot me agar ye prompt unhone likha hota ki answer user's question then wo har cheez ka answer deta so to avoid these kind of diescrepancy and security issue hame llm ko limit karna jaruri hai apne use case ke hisab se 

'''
BAD PROMPT : this is a user complain : My laptop is not working, handle this(it is very vague prompt means ambiguity aayega aise prompt se) 
isko sudharne ke liye 6 steps hota hai 
 1)role 2)task 3)constraints 4)output format 5)zero/one shot 6)fallback 
 jab ye 6 cheez ka use karke hum ek prompt likhte hai toh hamara prompt stable kehlata hai nhi toh answer stable nhi aayega 
 1)role ka matlab means who are you(llm ko batate hai like customer support agent) and kabhi bhi hum role likhenge na wo domain related hona chahiye and uski responsibility honi chahiye like you are a senior engineer for reviewing code na ki you are a genus engineer build gta 7 means agar ham role hi define kar skte the itna easily then ham kisi bhi llm ko diectly bol ke uske jaisa behave karne ke liye bol skte the like claude ke free version me jaake usko ye bol skte the ki hey claude you are latest claude mythos agent then it will be behave like claude mythons which is not possible at all, isiliye jab bhi role likhna chahiye na wo domain related and responsiblity define karke likhni chahiye so that wo waisa behave kar sake isiliye jab ham role likhenge uske andar domain and responsibility clearly define karna chahiye
 2)task ka matlab means actual me llm ko kya karna hai means tumhara kam kya hai wo karo like classification of issue na ki tumhe problem solve karna hai tumhe bas issue ko clasify karna hai means usko clear cut batayenge ki kya karna hai like issue ko classify karna hai, solve karna hai, etc. kuch bhi ambiguity nhi rakhenge so that wo acche se behave kar paye 
 3)constraints llm ko boundary provide karta hai and ye sabse important steps hai good prompt likhne ka, boundary ka matlab means answer ko bound kar skte hai ki mujhe answer particular format me hi chahiye so that wo hamare hisab se answer de sake nhi toh llm apne hisab se answer deta, so constraint hamare answer ko bandhtaa hai so that output overflow and differnet output naa aaye.
 4)output format : it means hame answer kis format me chahiye like one word answer, punctuate me answer chahiye naa ki apne hisab se batana 
 5)zero shot/ one shot : means ham llm ko example deke agar prompt likh rahe hai toh one shot ke under aata hai nhi toh wo zero shot ke andar aata hai and agar ham llm ko ek se zyada example de rahe hai toh usko few shots bolte hai and jab llm ko example deke prompt dete hai na then llm example ke hisab se acche se scan karke output deta hai
 6)fallback : agar koi bhi unrelated issue which does not run fit in the answer means let say apple ke bot ko alag swall pucha gf chhod ke bhag gayi then yaha pe wo bot customer issue solve karne ke liye baitha hai but prompt usko prompt bahot alag gaya hai then is case me wo other return karega like sorry i can't answer your question, isko fallback kaha jata hai and software engineering me ek concept hai ki agar sab cheez hamare hisab se chal raha hai then usko happy path bolte hai 
 '''
# uv venv --python
# venv --python 3.12
# code .py ka name means file ka name

#day 7 on ReAct(Reasoning + Action)
"""
What is meant by ReAct(also ReAct kya hota hai, )"
with respect to training data chatgpt ka pehle kya problem hota tha ki wo bas training data pe hi answer deta tha means agar hum usse kuch present ka puchte na then uske pass kuch answer nhi hota tha and ye maine khud observe kiya hai pehle jab chatgpt use karta tha, but present ka answer na de pana is one of the biggest drawback for chatgpt means log ise efficient nhi man rahe the, then chatgpt ne kya start kiya ki particular api ki madad se present information gather karna like weather ke information ke liye wo particular present weather ke api ko use karega then dubai ke aas pass kitne hotel free hai and unki price kya hai so iske liye hum particular make my trip ka api use kar skte hai 
but api use karne se ek problem utpann hui but chatgpt ke pass ek tool nhi hota so kaun sa tool kab use karna hai and kausna tool use karna hai ye ek problem ban gayi, because tools ka number fix nhi hai ki llm kitne tools use kar raha ho, suppose ek example hai ki amazon ka ek ai agent hai jo customer ki query solve karta hai and uske pass bahot saare tools ho skte hai like order_status tool, delivery_status tool, return tool, refund tool, etc, etc, because jab user ne query dala ki 'i want my order details' then particular llm konsa tool use karega wo fix nhi like hum normal if else se usko define nhi kar skte hai uski bahot saari permutations ho skti hai also ek took ka output dusre took ka input ho skta hai like order details me order id output hai order id took ka jo ki input hoga delivery info took ka based on order id it will process the query further.
isi problem ko solve karne ke liye ki llm kaunsa tool use karega and kab kaunsa tool use karega and kitna use karega, ReAct ka concept aaya
ReAct stands for Reasoning and act 
suppose ek example hai ki user bol raha hai 'I want to by an iphone 17. I have 5000rs. If i buy it, how much money will I be left with? toh iske liye chatgpt kya karega ki wo iphone 17 ka current price nikalega kisi api tool ka use karke then price nikalne ke baad next statement pe process karega ki user bol raha hai uske pass 5000 hai aisa then usko ek variable me store kar lega then wo again ek calculator ka api tool call karega so that wo kitna amount left hai wo return kare sake so isi process ko REACT bolte hai means llm khud reasoning kar raha hai ki konsa tool kab use karna hai and kyu karna hai and action perfor kar raha hai accrodingly so that wo answer return kar sake 
aaj ke time pe llm me react loop extensively use ho raha hai because agar hamare pass sirf llm hai na toh usse kuch nhi hoga becaue modern agents banane ke liye llm ko hamesha llm + api tools hamesha lagenge so that wo time ke sath update hoke effectively output de sake and jaise jaise product(aka project llm like) complex hota jayega hume react loop introduce karna hoga and(introduce karna means particular function dena hoga so that wo us function ka use karke output de sake) 

for any llm 
1)firstly hame tools dena hota hai means python function likh denge and llm usi ka use karke wo output generate karega
2)secondly system prompt likhenge and batana hota hai
    decide karna hai ki kya kaam hai
    iske liye kaunsa available tooll use hoga
    tool ko execute karna 
    usse jo bhi answer aaye usko reuse kar lena and ye tab tak karna jab tak ki answer n aa jaye and ye sab hum khud nhi kar rahe hai hum llm ko bata rahe hai ki tumhe kaise karna hai and ye cycle hamesha chalta rahega jab tak hamara answer na aa jaye ye karte karte llm humko ek answer deta hai
"""

#day 8 episode 09 on Prompt Chaining
'''
prompt ko hum do prakar se likh sakte hai like ek hi baar me sab information provide karke then us prompt ka output generate karwana llm ki madad se and dusra prakar hai ki prompt ko chhote chhote part me tod ke phir usko llm ke madad se output generate karwana then generated output ko phir se next prompt me input ke roop me use karna and ye process tab tak karte rahenge jab tak ki final answer na aa jaye, is prakar ke prompt ko hum prompt chaining bolte hai
but now the question is how it is different from react loop, react loop me humne ek hi prompt me sab information provide kiya tha and uske output ko phir se next prompt me input ke roop me use kiya tha but prompt chaining me humne chhote chhote prompt likhe hai and unka output ko phir se next prompt me input ke roop me use kiya hai jab tak ki final answer na aa jaye, so react loop me humne ek hi prompt me sab information provide kiya tha and prompt chaining me humne chhote chhote prompt likhe hai and unka output ko phir se next prompt me input ke roop me use kiya hai tab tak ki final answer na aa jaye, so dono me difference ye hai ki react loop me humne ek hi prompt me sab information provide kiya tha and prompt chaining me humne chhote chhote prompt likhe hai and unka output ko phir se next prompt me input ke roop me use kiya hai tab tak ki final answer na aa jaye

but prompt chaining ki zarurat kya hai?
because agar hum ek hi prompt me sab information provide karenge na toh wo prompt bahot bada ho jayega and llm ko samajhne me problem aayegi and also error aaya toh usko debug karna bahot mushkil ho jata hai like konse module me galti hai like wo resume wala example jo bataya tha course mai agar 5 step ka ek hi prompt bana ke de diya then agar kisi bhi ek step me galti ho gyai then usko debug karne me difficult hoga like kisme error hai also bahot time waste hoga ki starting se code dekho then usko resolve karo, so isi cheez ko tackle karne ke liye hum prompt chaining ka use karte hai means chhote chhote prompt likhte hai and unka output ko phir se next prompt me input ke roop me use karte hai tab tak ki final answer na aa jaye, so prompt chaining ka use karne se humara prompt chhota ho jata hai and agar kisi bhi step me galti ho gyai then usko debug karna easy ho jata hai like konse module me galti hai wo easily pata chal jata hai and also time bhi save hota hai
4 cheez jo prompt chaining ke wajah se milti hai like 1) debugging 2) Module wise information 
3) We can use different model according to our use case so that jo important kam hai wo best wale llm ka use karke karwayenge and jo easy wala hai usko alag llm ka use karke karwayenge isse cost, time bachega and efficiency badhegi.
4) Retry choice like hum kitni bhi baar retry kar skte hai like jab tak best wala outcome nhi mil jata.

**but how it is different from react loop?**
ham log react me hum bas tools and functions banate the jaha pe llm khud decide karta tha ki konsa tool use karna hai but prompt chaining me developer decide karta hai ki konsa prompt dena hai and konsa cheez use karna hai like pehla cheez skills extract karna hai then jd match karna hai then etc. so iske base pe hi llm ko pata hoga ki usko step wise konsa tool use karna hai isiliye ye react se different hai whereas react me hum bas tool de dete hai then wo khud se decision le leta hai yaha pe hum khud decide karte hai ki konsa kaam kab use karna hai also hum log ye specify kar skte hai konsa tool use karna chahiye so that output efficiently hum generate karwa sake 

'''
#day 9 episode 10 on Streaming (Like ChatGPT)
"""
Streaming means kya hota hai, like jab ham chatgpt ko prompt dete hai toh wo hame ek hi baar me answer nahi de raha hota hai wo line by line ek ek karke answer generate kar raha hota hai toh usi cheez ko streaming bolte hai also jab netflix ya youtube pe jab ko live stream ho raha hota hai toh ek hi baar me video nhi dikh raha hota hai yaha pe network byte by byte chunks me videos ke part bhej raha hota hai so that hame video receive hoke dikhta hai also isko ham stream of objects ke jaisa visualize kar skte hai. jab chatgpt pe line by line aa raha hota hai output toh us time pe stream = true initialize hota hai llm ke stream variable ko and isi chote part ko chunks bola jata hai

why this streaming is used?
because answer ek baar me bhi diya jaa skta hai but jab kabhi bhi user koi service le raha hota hai toh kabhi bhi last delivered ke hisab se speed decide nhi ho raha hota hai but kitna jaldi output firstly serve kiya jaa raha hai uske upar decide hota hai. suppose hume jab 1000 line ka answer chahiye hoga and answer aane 5 min lag raha hai toh ye kitna boring hai means hame ye lagega ki service acchi nhi hai but jab koi dusra llm same cheez turant line by line provide karta hai irrespective of ek saath answer dene ke toh ye thoda effective lagta hai, streaming line by line bhejna sirf human experience ko accha karne ke liye implement kiya gaya hai

by default streaming false hota hai because llm hamesha streaming use nhi kar raha hota, hame streaming tab hi use karna hai jab hamara end user human ho, tab hi hame streaming use karna chahiye, but agar user koi dusra llm hai toh tab hame streaming use nhi karna chahiye because json generate karte samay streaming use nhi karna chhaiye 

"""

#day 12 on Personal Portfolio AI Project episode 11
'''
API is a set of functions and procedures that allow the creation of applications which access the features or data of an operating system, application, or other service. API is a software intermediary that allows two applications to talk to each other. For example, when you use an app like Facebook, send an instant message, or check the weather on your phone, you’re using an API.
Browser or code ke beech me baat karane ke liye API ka use hota hai, jaise ki jab hum browser me koi website open karte hai toh browser ke pass ek request jata hai ki ye website ka data chahiye then website ke server se response aata hai ki ye website ka data hai then browser usko render karke hame dikha deta hai, is process me browser aur server ke beech me API ka use hota hai.
python me fastAPI and django ka use karke API banate hai and uske through hum apne application ke features ko access karte hai.
Similarly different language ke liye alag alag API hota hai jaise ki python ke liye fastAPI and django, java ke liye spring boot, javascript ke liye express.js, etc.
uvicon is used to run the fastAPI server and it is a lightning fast ASGI server implementation, using uvloop and httptools. It is designed to be easy to use and to provide high performance. It is also compatible with the ASGI specification, which allows it to be used with a variety of web frameworks and applications.
in hinglish uvicon ka use fastAPI server ko run karne ke liye hota hai and ye ek lightning fast ASGI server implementation hai, jo uvloop and httptools ka use karta hai. Ye easy to use hai and high performance provide karta hai. Ye ASGI specification ke sath compatible hai, jo ki alag alag web frameworks and applications ke sath use kiya ja sakta hai.
'''